name: Build OpenSupaplex Release
on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      prerelease:
        required: true
        default: false
        type: boolean
      release_notes:
        required: false
        type: string

jobs:
  build-nds:
    name: Nintendo DS
    runs-on: ubuntu-22.04
    container: sergiou87/nds-docker-open-supaplex:7.2
    steps:
      - uses: actions/checkout@v1
      - name: Build OpenSupaplex
        run: |
          ./nds/ci-build-nds.sh
        shell: bash
      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: nds-build
          path: nds/OpenSupaplex.nds
 
  # create-release:
    
  #   name: Create release
  #   needs:
  #     [
  #       build-nds,
  #     ]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checking out...
  #       uses: actions/checkout@v1
  #     - name: Read release notes
  #       id: read_release_notes
  #       run: |
  #         CONTENTS=`cat changelog/${{ inputs.version }}.txt`
  #         CONTENTS="${CONTENTS//'%'/'%25'}"
  #         CONTENTS="${CONTENTS//$'\n'/'%0A'}"
  #         CONTENTS="${CONTENTS//$'\r'/'%0D'}"
  #         echo "::set-output name=release_notes::${CONTENTS}"
  #       shell: bash
  #       if: ${{ !inputs.release_notes }}
  #     - name: Download Nintendo DS Build Asset
  #       uses: actions/download-artifact@v1
  #       with:
  #         name: nds-build

  #     - name: Upload Nintendo DS Build Asset
  #       uses: actions/upload-release-asset@v1
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #       with:
  #         upload_url: ${{ steps.create_release.outputs.upload_url }}
  #         asset_path: nds-build/OpenSupaplex.nds
  #         asset_name: OpenSupaplex-nds-${{ inputs.version }}.nds
  #         asset_content_type: application/binary
